using FluentValidation;
using Icarus.GestionAvicola.Application.Galpones;
using Icarus.GestionAvicola.Application.Mortalidad;
using Icarus.GestionAvicola.Application.Produccion;
using Icarus.GestionAvicola.Domain;
using MediatR;
namespace Icarus.GestionAvicola.Application.Eficiencia;
public sealed record ObtenerEficienciaGalponQuery(Guid GalponId, DateOnly? Desde, DateOnly? Hasta) : IRequest<EficienciaGalponResumen>;
public sealed record EficienciaDiaResumen(DateOnly Fecha, int TotalMaples, int TotalUnidadesIncompletas, int TotalVendible, int TotalMaplesDescarte, int TotalUnidadesDescarte, int TotalDescarte, int GallinasVivas, decimal Eficiencia, bool BajoUmbral);
public sealed record EficienciaGalponResumen(Guid GalponId, DateOnly Desde, DateOnly Hasta, IReadOnlyList<EficienciaDiaResumen> Dias);
public sealed class ObtenerEficienciaGalponValidator : AbstractValidator<ObtenerEficienciaGalponQuery> { public ObtenerEficienciaGalponValidator() => RuleFor(x => x.Desde).Must((q, desde) => !desde.HasValue || !q.Hasta.HasValue || desde <= q.Hasta).WithMessage("El rango de fechas es inválido."); }
public sealed class ObtenerEficienciaGalponHandler(IRepositorioGalpones gs, IRepositorioProduccion ps, IRepositorioMortalidad ms) : IRequestHandler<ObtenerEficienciaGalponQuery, EficienciaGalponResumen> { public async Task<EficienciaGalponResumen> Handle(ObtenerEficienciaGalponQuery request, CancellationToken cancellationToken) { var g = await gs.ObtenerPorIdAsync(request.GalponId, cancellationToken) ?? throw new Icarus.BuildingBlocks.Domain.NotFoundException("Galpon", request.GalponId); var hasta = request.Hasta ?? DateOnly.FromDateTime(DateTime.UtcNow); var desde = request.Desde ?? hasta.AddDays(-6); var p = await ps.ListarPorRangoAsync(g.Id, desde, hasta, cancellationToken); var m = await ms.ListarPorRangoAsync(g.Id, desde, hasta, cancellationToken); var fechas = p.Select(x => x.Fecha).Union(m.Select(x => x.Fecha)).OrderBy(x => x).ToList(); var dias = fechas.Select(f => { var pp = p.Where(x => x.Fecha == f).ToList(); var mm = m.Where(x => x.Fecha == f).ToList(); var vend = pp.Sum(x => x.TotalHuevosVendibles()); var vivas = pp.Select(x => (x.Hora, x.GallinasVivas)).Concat(mm.Select(x => (x.Hora, x.GallinasVivas))).OrderByDescending(x => x.Hora).First().GallinasVivas; var e = EficienciaPostura.Calcular(vend, vivas); return new EficienciaDiaResumen(f, pp.Sum(x => x.CantidadMaples), pp.Sum(x => x.UnidadesIncompletas), vend, pp.Sum(x => x.MaplesDescarte), pp.Sum(x => x.UnidadesDescarte), pp.Sum(x => x.TotalHuevosDescarte()), vivas, e, EficienciaPostura.EstaBajoUmbral(e)); }).ToList(); var hoy = DateOnly.FromDateTime(DateTime.UtcNow); if (hasta == hoy && dias.All(x => x.Fecha != hoy)) { dias.Add(new(hoy, 0, 0, 0, 0, 0, 0, g.GallinasActuales, 0, true)); } return new(g.Id, desde, hasta, dias); } }
