// <auto-generated />
using System;
using Icarus.GestionAvicola.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Icarus.GestionAvicola.Infrastructure.Migrations
{
    [DbContext(typeof(GestionAvicolaDbContext))]
    [Migration("20260818191535_ProduccionYMortalidad")]
    partial class ProduccionYMortalidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gestion_avicola")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.Galpon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNacimientoLote")
                        .HasColumnType("date");

                    b.Property<int>("GallinasActuales")
                        .HasColumnType("int");

                    b.Property<Guid>("GranjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("GranjaId", "Numero")
                        .IsUnique();

                    b.ToTable("galpones", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_galpones_capacidad", "[CapacidadMaxima] > 0");

                            t.HasCheckConstraint("CK_galpones_inventario", "[GallinasActuales] >= 0 AND [GallinasActuales] <= [CapacidadMaxima]");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.Granja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("[EstaActivo] = 1");

                    b.HasIndex("ClienteId", "Nombre")
                        .IsUnique();

                    b.ToTable("granjas", "gestion_avicola");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.RegistroMortalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMuertas")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GallinasVivas")
                        .HasColumnType("int");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("GalponId", "Fecha");

                    b.ToTable("registros_mortalidad", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_registros_mortalidad_cantidad", "[CantidadMuertas] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.RegistroProduccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMaples")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GallinasVivas")
                        .HasColumnType("int");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaplesDescarte")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesDescarte")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesIncompletas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("GalponId", "Fecha");

                    b.ToTable("registros_produccion", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_registros_produccion_maples", "[CantidadMaples] >= 0 AND [MaplesDescarte] >= 0");

                            t.HasCheckConstraint("CK_registros_produccion_sueltos", "[UnidadesIncompletas] >= 0 AND [UnidadesIncompletas] < 30 AND [UnidadesDescarte] >= 0 AND [UnidadesDescarte] < 30");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
