// <auto-generated />
using System;
using Icarus.GestionAvicola.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Icarus.GestionAvicola.Infrastructure.Migrations
{
    [DbContext(typeof(GestionAvicolaDbContext))]
    [Migration("20260904140637_PedidosAlimentoInicial")]
    partial class PedidosAlimentoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gestion_avicola")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.DetallePedidoAlimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<int>("Equivalentes40Kg")
                        .HasColumnType("int");

                    b.Property<Guid?>("NotificacionPreciosAlimentosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoAlimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrecioFinalPor40Kg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Presentacion")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubtotalSolicitado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoAlimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoAlimentoId", "TipoAlimento")
                        .IsUnique();

                    b.ToTable("detalles_pedidos_alimentos", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_detalles_pedidos_cantidad", "[CantidadSolicitada] > 0");

                            t.HasCheckConstraint("CK_detalles_pedidos_precio", "[PrecioFinalPor40Kg] IS NULL OR [PrecioFinalPor40Kg] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.DetallePrecioAlimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EdadDesdeDias")
                        .HasColumnType("int");

                    b.Property<int?>("EdadHastaDias")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificacionPreciosAlimentosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrecioActualDocumento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecioFinalPor40Kg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Presentacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoAlimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificacionPreciosAlimentosId", "TipoAlimento", "Presentacion")
                        .IsUnique();

                    b.ToTable("detalles_precio_alimento", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_detalles_precio_final", "[PrecioFinalPor40Kg] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.Galpon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNacimientoLote")
                        .HasColumnType("date");

                    b.Property<int>("GallinasActuales")
                        .HasColumnType("int");

                    b.Property<Guid>("GranjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("GranjaId", "Numero")
                        .IsUnique();

                    b.ToTable("galpones", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_galpones_capacidad", "[CapacidadMaxima] > 0");

                            t.HasCheckConstraint("CK_galpones_inventario", "[GallinasActuales] >= 0 AND [GallinasActuales] <= [CapacidadMaxima]");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.Granja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("[EstaActivo] = 1");

                    b.HasIndex("ClienteId", "Nombre")
                        .IsUnique();

                    b.ToTable("granjas", "gestion_avicola");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.ItemPlanVacunacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EdadDia")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("ModoAplicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProgramaVacunacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Vacuna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaVacunacionId");

                    b.ToTable("programas_vacunacion_items", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_programas_vacunacion_items_edad", "[EdadDia] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.NotificacionPreciosAlimentos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AporteCaisy")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("DocumentoOriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDocumento")
                        .HasColumnType("date");

                    b.Property<decimal>("Fondo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Servicios")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("VigenteDesde")
                        .IsUnique()
                        .HasFilter("[Estado] = 1 AND [EstaActivo] = 1");

                    b.ToTable("notificaciones_precios_alimentos", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_notificaciones_precios_aportes", "[AporteCaisy] > 0 AND [Fondo] > 0 AND [Servicios] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.PedidoAlimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaPedido")
                        .HasColumnType("date");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "FechaPedido");

                    b.ToTable("pedidos_alimentos", "gestion_avicola");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.ProgramaVacunacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadAves")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("programas_vacunacion", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_programas_vacunacion_cantidad_aves", "[CantidadAves] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.RegistroMortalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMuertas")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GallinasVivas")
                        .HasColumnType("int");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("GalponId", "Fecha");

                    b.ToTable("registros_mortalidad", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_registros_mortalidad_cantidad", "[CantidadMuertas] > 0");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.RegistroProduccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadMaples")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GallinasVivas")
                        .HasColumnType("int");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaplesDescarte")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesDescarte")
                        .HasColumnType("int");

                    b.Property<int>("UnidadesIncompletas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("GalponId", "Fecha");

                    b.ToTable("registros_produccion", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_registros_produccion_maples", "[CantidadMaples] >= 0 AND [MaplesDescarte] >= 0");

                            t.HasCheckConstraint("CK_registros_produccion_sueltos", "[UnidadesIncompletas] >= 0 AND [UnidadesIncompletas] < 30 AND [UnidadesDescarte] >= 0 AND [UnidadesDescarte] < 30");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.TareaVacunacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvesVacunadas")
                        .HasColumnType("int");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompletadaPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EdadDia")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("FechaAplicacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemPlanVacunacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModoAplicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacionesAplicacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesProgramadas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProgramaVacunacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Vacuna")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "FechaProgramada");

                    b.HasIndex("GalponId", "Estado");

                    b.ToTable("tareas_vacunacion", "gestion_avicola", t =>
                        {
                            t.HasCheckConstraint("CK_tareas_vacunacion_aves", "[AvesVacunadas] IS NULL OR [AvesVacunadas] > 0");

                            t.HasCheckConstraint("CK_tareas_vacunacion_edad", "[EdadDia] > 0");

                            t.HasCheckConstraint("CK_tareas_vacunacion_estado_fecha", "[Estado] <> 'Completada' OR [FechaAplicacion] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.TransicionPedidoAlimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EstadoDestino")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrigen")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaEntregaEstimada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PedidoAlimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoAlimentoId");

                    b.ToTable("transiciones_pedidos_alimentos", "gestion_avicola");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.DetallePedidoAlimento", b =>
                {
                    b.HasOne("Icarus.GestionAvicola.Domain.PedidoAlimento", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoAlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.DetallePrecioAlimento", b =>
                {
                    b.HasOne("Icarus.GestionAvicola.Domain.NotificacionPreciosAlimentos", null)
                        .WithMany("Detalles")
                        .HasForeignKey("NotificacionPreciosAlimentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.ItemPlanVacunacion", b =>
                {
                    b.HasOne("Icarus.GestionAvicola.Domain.ProgramaVacunacion", null)
                        .WithMany("Items")
                        .HasForeignKey("ProgramaVacunacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.TransicionPedidoAlimento", b =>
                {
                    b.HasOne("Icarus.GestionAvicola.Domain.PedidoAlimento", null)
                        .WithMany("Historial")
                        .HasForeignKey("PedidoAlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.NotificacionPreciosAlimentos", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.PedidoAlimento", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Icarus.GestionAvicola.Domain.ProgramaVacunacion", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
