<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Icarus.BuildingBlocks.Domain\Icarus.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Icarus.BuildingBlocks.Application\Icarus.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Icarus.BuildingBlocks.Observability\Icarus.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\src\Host\Icarus.Host\Icarus.Host.csproj" />
    <ProjectReference Include="..\..\src\Identity\Icarus.Identity.Application\Icarus.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Identity\Icarus.Identity.Domain\Icarus.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Identity\Icarus.Identity.Infrastructure\Icarus.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Clientes\Icarus.Clientes.Domain\Icarus.Clientes.Domain.csproj" />
    <ProjectReference Include="..\..\src\Clientes\Icarus.Clientes.Application\Icarus.Clientes.Application.csproj" />
    <ProjectReference Include="..\..\src\Clientes\Icarus.Clientes.Infrastructure\Icarus.Clientes.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\GestionAvicola\Icarus.GestionAvicola.Domain\Icarus.GestionAvicola.Domain.csproj" />
    <ProjectReference Include="..\..\src\GestionAvicola\Icarus.GestionAvicola.Application\Icarus.GestionAvicola.Application.csproj" />
    <ProjectReference Include="..\..\src\GestionAvicola\Icarus.GestionAvicola.Infrastructure\Icarus.GestionAvicola.Infrastructure.csproj" />
  </ItemGroup>

</Project>
