// <auto-generated />
using System;
using Icarus.ControlAcceso.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Icarus.ControlAcceso.Infrastructure.Migrations
{
    [DbContext(typeof(ControlAccesoDbContext))]
    [Migration("20260928105025_OperacionMarcacion")]
    partial class OperacionMarcacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("control_acceso")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.ConfiguracionAccesoTrabajador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Enrolamiento")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionEnrolamiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TrabajadorId")
                        .IsUnique();

                    b.ToTable("configuracion_acceso_trabajador", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.JornadaAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaBoliviana")
                        .HasColumnType("date");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TrabajadorId", "FechaBoliviana")
                        .IsUnique();

                    b.ToTable("jornadas_acceso", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.Marcacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaveIdempotencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HoraDeclaradaUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("InstanteUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JornadaAccesoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JornadaAccesoId", "ClaveIdempotencia")
                        .IsUnique();

                    b.ToTable("marcaciones", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.OperacionEnrolamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaveIdempotencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionEnrolamiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "ClaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("ClienteId", "TrabajadorId");

                    b.ToTable("operaciones_enrolamiento", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.OperacionMarcacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<Guid>("ClaveIdempotencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpiraEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("JornadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "ClaveIdempotencia")
                        .IsUnique();

                    b.HasIndex("ClienteId", "TrabajadorId");

                    b.ToTable("operaciones_marcacion", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.PlantillaFacialProtegida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContenidoCifrado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaRevocacionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModeloFormato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("TrabajadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionClave")
                        .HasColumnType("int");

                    b.Property<int>("VersionEnrolamiento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "TrabajadorId", "EstaActivo");

                    b.HasIndex("ClienteId", "TrabajadorId", "VersionEnrolamiento")
                        .IsUnique();

                    b.ToTable("plantillas_faciales", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.RevisionJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HastaSecuenciaOriginal")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InstanteCorreccionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JornadaAccesoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("JornadaAccesoId");

                    b.ToTable("revisiones_jornada", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.SesionKiosco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ExpiraEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HashCredencial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("RevocadaEnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HashCredencial")
                        .IsUnique();

                    b.HasIndex("ClienteId", "EstaActiva");

                    b.ToTable("sesiones_kiosco", "control_acceso");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.Marcacion", b =>
                {
                    b.HasOne("Icarus.ControlAcceso.Domain.JornadaAcceso", null)
                        .WithMany("Marcaciones")
                        .HasForeignKey("JornadaAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.RevisionJornada", b =>
                {
                    b.HasOne("Icarus.ControlAcceso.Domain.JornadaAcceso", null)
                        .WithMany("Revisiones")
                        .HasForeignKey("JornadaAccesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Icarus.ControlAcceso.Domain.ValorEfectivo", "ValoresEfectivos", b1 =>
                        {
                            b1.Property<Guid>("RevisionJornadaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("InstanteUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int");

                            b1.HasKey("RevisionJornadaId", "Id");

                            b1.ToTable("revisiones_jornada_valores", "control_acceso");

                            b1.WithOwner()
                                .HasForeignKey("RevisionJornadaId");
                        });

                    b.Navigation("ValoresEfectivos");
                });

            modelBuilder.Entity("Icarus.ControlAcceso.Domain.JornadaAcceso", b =>
                {
                    b.Navigation("Marcaciones");

                    b.Navigation("Revisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
