using FluentValidation;
using Icarus.BuildingBlocks.Application.Observability;
using Icarus.BuildingBlocks.Domain;
using Icarus.GestionAvicola.Application.Galpones;
using Icarus.GestionAvicola.Domain;
using MediatR;
namespace Icarus.GestionAvicola.Application.Mortalidad;
public sealed record RegistrarMortalidadCommand(Guid GalponId, TimeOnly? Hora, int CantidadMuertas, Guid? IdempotencyKey) : IRequest<Guid>, IOperacionRegistrable { public DescriptorOperacionRegistroVuelo Registro { get; } = new("avicola.mortalidad.registrar", new Dictionary<string, DatoRegistroVuelo>()); }
public sealed record EditarMortalidadCommand(Guid MortalidadId, TimeOnly Hora, int CantidadMuertas) : IRequest, IOperacionRegistrable { public DescriptorOperacionRegistroVuelo Registro { get; } = new("avicola.mortalidad.editar", new Dictionary<string, DatoRegistroVuelo>()); }
public sealed record DesactivarMortalidadCommand(Guid MortalidadId) : IRequest, IOperacionRegistrable { public DescriptorOperacionRegistroVuelo Registro { get; } = new("avicola.mortalidad.desactivar", new Dictionary<string, DatoRegistroVuelo>()); }
public sealed record ListarMortalidadPorDiaQuery(Guid GalponId, DateOnly? Fecha) : IRequest<MortalidadDiaResumen>;
public sealed class RegistrarMortalidadValidator : AbstractValidator<RegistrarMortalidadCommand> { public RegistrarMortalidadValidator() => RuleFor(x => x.CantidadMuertas).GreaterThan(0); }
public sealed class EditarMortalidadValidator : AbstractValidator<EditarMortalidadCommand> { public EditarMortalidadValidator() => RuleFor(x => x.CantidadMuertas).GreaterThan(0); }
public sealed class RegistrarMortalidadHandler(IRepositorioGalpones galpones, IRepositorioMortalidad mortalidad, IRegistroVuelo registroVuelo, IUnidadTrabajoGestionAvicola unidadTrabajo) : IRequestHandler<RegistrarMortalidadCommand, Guid>
{ public async Task<Guid> Handle(RegistrarMortalidadCommand request, CancellationToken cancellationToken) { var galpon = await galpones.ObtenerPorIdAsync(request.GalponId, cancellationToken) ?? throw new NotFoundException("Galpon", request.GalponId); if (request.IdempotencyKey is Guid key) { var existente = await mortalidad.ObtenerPorIdempotencyKeyAsync(galpon.Id, key, cancellationToken); if (existente is not null) return existente.Id; } galpon.AjustarInventarioGallinas(galpon.GallinasActuales - request.CantidadMuertas); registroVuelo.Decidir("avicola.mortalidad.registrar", "ajuste_inventario", "aplicada", new Dictionary<string, object?> { ["GallinasVivas"] = galpon.GallinasActuales }); var ahora = DateTime.UtcNow; var registro = new RegistroMortalidad(galpon.Id, galpon.ClienteId, DateOnly.FromDateTime(ahora), request.Hora ?? TimeOnly.FromDateTime(ahora), request.CantidadMuertas, galpon.GallinasActuales, request.IdempotencyKey); mortalidad.Agregar(registro); await unidadTrabajo.SaveChangesAsync(cancellationToken); return registro.Id; } }
public sealed class EditarMortalidadHandler(IRepositorioMortalidad mortalidad, IRepositorioGalpones galpones, IRegistroVuelo registroVuelo, IUnidadTrabajoGestionAvicola unidadTrabajo) : IRequestHandler<EditarMortalidadCommand>
{ public async Task Handle(EditarMortalidadCommand request, CancellationToken cancellationToken) { var registro = await mortalidad.ObtenerPorIdAsync(request.MortalidadId, cancellationToken) ?? throw new NotFoundException("Registro de mortalidad", request.MortalidadId); var galpon = await galpones.ObtenerPorIdAsync(registro.GalponId, cancellationToken) ?? throw new NotFoundException("Galpon", registro.GalponId); galpon.AjustarInventarioGallinas(galpon.GallinasActuales + registro.CantidadMuertas - request.CantidadMuertas); registroVuelo.Decidir("avicola.mortalidad.editar", "ajuste_inventario", "aplicada", new Dictionary<string, object?> { ["GallinasVivas"] = galpon.GallinasActuales }); registro.Editar(request.CantidadMuertas, request.Hora, galpon.GallinasActuales); await unidadTrabajo.SaveChangesAsync(cancellationToken); } }
public sealed class DesactivarMortalidadHandler(IRepositorioMortalidad mortalidad, IRepositorioGalpones galpones, IRegistroVuelo registroVuelo, IUnidadTrabajoGestionAvicola unidadTrabajo) : IRequestHandler<DesactivarMortalidadCommand>
{ public async Task Handle(DesactivarMortalidadCommand request, CancellationToken cancellationToken) { var registro = await mortalidad.ObtenerPorIdAsync(request.MortalidadId, cancellationToken) ?? throw new NotFoundException("Registro de mortalidad", request.MortalidadId); registro.Desactivar(); var galpon = await galpones.ObtenerPorIdAsync(registro.GalponId, cancellationToken) ?? throw new NotFoundException("Galpon", registro.GalponId); galpon.AjustarInventarioGallinas(galpon.GallinasActuales + registro.CantidadMuertas); registroVuelo.Decidir("avicola.mortalidad.desactivar", "ajuste_inventario", "aplicada", new Dictionary<string, object?> { ["GallinasVivas"] = galpon.GallinasActuales }); await unidadTrabajo.SaveChangesAsync(cancellationToken); } }
public sealed class ListarMortalidadPorDiaHandler(IRepositorioGalpones galpones, IRepositorioMortalidad mortalidad) : IRequestHandler<ListarMortalidadPorDiaQuery, MortalidadDiaResumen>
{ public async Task<MortalidadDiaResumen> Handle(ListarMortalidadPorDiaQuery request, CancellationToken cancellationToken) { var galpon = await galpones.ObtenerPorIdAsync(request.GalponId, cancellationToken) ?? throw new NotFoundException("Galpon", request.GalponId); var fecha = request.Fecha ?? DateOnly.FromDateTime(DateTime.UtcNow); var rs = await mortalidad.ListarPorDiaAsync(galpon.Id, fecha, cancellationToken); return new(galpon.Id, fecha, rs.Select(r => new MortalidadResumen(r.Id, r.Fecha, r.Hora, r.CantidadMuertas, r.GallinasVivas)).ToList(), rs.Sum(r => r.CantidadMuertas)); } }
