<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Icarus.BuildingBlocks.Application\Icarus.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Icarus.BuildingBlocks.Observability\Icarus.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\Identity\Icarus.Identity.Infrastructure\Icarus.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Clientes\Icarus.Clientes.Infrastructure\Icarus.Clientes.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
